ssh:
  build: ./ssh
  container_name: lemp_ssh
  ports:
    - "2222:22"
  volumes:
    - /home/core/www:/var/www:rw
mariadb:
  build: ./mariadb
  container_name: lemp_mariadb
  env_file: ./mariadb/mariadb.env
  links:
    - ssh
  ports:
    #- "8082:3306"
    - "2223:22"
  volumes:
    - /var/run/mysqld
    - /var/lib/mysql
phpmyadmin:
  build: ./phpmyadmin
  container_name: lemp_phpmyadmin
  environment:
     - PMA_ARBITRARY=0
     - PMA_HOST=0.0.0.0
     - PMA_PORT=3306
  links:
    - ssh
  #ports:
  #  - "8084:8080"
  volumes:
    - /var/www/phpmyadmin
php:
  build: ./php
  container_name: lemp_php
  links:
    - ssh
  volumes:
    - /var/run/php-fpm
  volumes_from:
    - ssh:rw
    - mariadb:rw
    - phpmyadmin:rw
nginx:
  build: ./nginx
  container_name: lemp_nginx
  links:
    - php
  ports:
    - "8080:80"
    - "8081:443"
  volumes_from:
    - php:rw
