ssh:
  build: ./ssh
  container_name: lemp_ssh
  ports:
    - "2222:22"
  volumes:
    - /home/core/www:/var/www:rw
mariadb:
  build: ./mariadb
  container_name: lemp_mariadb
  env_file: ./mariadb/mariadb.env
  links:
    - ssh
  ports:
    - 8082:3306
  volumes:
    - /var/run/mysqld
    - /var/lib/mysql
php:
  build: ./php
  container_name: lemp_php
  links:
    - ssh
  volumes:
    - /var/run/php-fpm
  volumes_from:
    - ssh
    - mariadb
nginx:
  build: ./nginx
  container_name: lemp_nginx
  links:
    - php
  ports:
    - "8080:80"
    - "8081:443"
  volumes_from:
    - php
