lanti-debian-base:
  build: ./debian
  container_name: lanti-debian-base
lanti-debian-web:
  build: ./web
  container_name: lanti-debian-web
  links:
    - lanti-debian-base
  ports:
    - "8080:80"
    - "8081:443"
    - "8082:22"
  volumes:
    - "/home/core/www:/var/www:rw"
#lanti-debian-mariadb:
#  build: ./mariadb
#  container_name: lanti-debian-mariadb
#  links:
#    - lanti-debian-web
#  ports:
#    - "8083:3306"
#    - "8084:22"
#  volumes:
#    - "/home/core/sql:/var/lib/mysql:rw"
