lanti-debian-base:
  build: ./debian
  container_name: lanti-debian-base
  #ports:
  #  - "8079:22"
lanti-debian-web:
  build: ./web
  container_name: lanti-debian-web
  links:
    - lanti-debian-base
  ports:
    - "8080:80"
    - "8081:443"
    - "8082:22"
  volumes_from:
    - lanti-debian-mariadb
  volumes:
    - "/home/core/www:/var/www:rw"
lanti-debian-mariadb:
  build: ./mariadb
  container_name: lanti-debian-mariadb
  env_file: ./mariadb/mariadb.env
  links:
    - lanti-debian-web
  ports:
    - "8083:3306"
    - "8084:22"
  volumes:
    - /var/run/mysqld
#lanti-debian-phpmyadmin:
#  build: ./lanti-debian-phpmyadmin
#  container_name: lanti-debian-phpmyadmin
#  links:
#    - lanti-debian-mariadb
#  ports:
#    - "8085:8080"
#    - "8086:22"
